version: "3"

services:
  api:
    build: ./apps/api
    ports:
      - "5001:5001"
    environment:
      - GEMINI_API=${GEMINI_API}
    restart: always

  web:
    build: ./apps/web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    restart: always
